### ISSUE TITLE
Unit 8 - Logical Operators and Booleans - Exercise

### ISSUE THREAD

**Issue by sarahholden** [sarahholden/fundamentals#11]
https://github.com/sarahholden/fundamentals/blob/master/08_unit/logical-operators-boolean-exercise.md

@amyealmeida Ready for review! Old exercise was super confusing and didn't really cover the material so I've updated the example to hopefully be more interesting and clear.

One thing I noticed is the jump links DO work when linking to another page on Github, but Gitbook doesn't jump to that section so I think adding links to the top of the solutions page for each section would be good. I've started doing this with the exercises I'm working on, but you're always a pro at formatting things nicely so feel free to update :)

**Comment by amyealmeida** [comment]
thanks, Sarah! Will do.
