### ISSUE TITLE
Ch8_Assignment Clear where we are doing work?

### ISSUE THREAD

**Issue by ZebGirouard** [sarahholden/fundamentals#118]
I don't think we mention that Sublime needs to be open to run these, and some of the commands are vague in that regard.  I think someone, maybe @sarahholden , should take a look at all the assignments and make sure we have good continuity with these directions.

Sublime and GitHub is probably a confusing mess for our pre-students.

**Comment by sarahholden** [comment]
Thanks @ZebGirouard! Assigning myself to this one.

**Comment by sarahholden** [comment]
Great call! I've updated for all assignments to make sure students know to work out of Sublime and which files they should have open. Thanks for the feedback!
