### ISSUE TITLE
Unit 8 - Conditionals Exercise

### ISSUE THREAD

**Issue by sarahholden** [sarahholden/fundamentals#12]
https://github.com/sarahholden/fundamentals/blob/master/08_unit/conditionals-exercise.md

@amyealmeida Ready for review

1 known issue:
- Can't embed JS Bin without pro account

**Comment by amyealmeida** [comment]
this looks good-- just keeping it open because of the jsbin issue

**Comment by sarahholden** [comment]
Should be good to go! All JS Bin issues are fixed.
