### ISSUE TITLE
Section 7.1 - Bilbo should be Frodo

### ISSUE THREAD

**Issue by susiremondi** [sarahholden/fundamentals#120]
Bilbo is the main character of the Hobbit book, but for LoTR it needs to be Frodo. Please change "Bilbo" to "Frodo" in the phrase "they would simply compare the characters' heights and pick the little Hobbit on the right, Bilbo." 

Technically Bilbo is shorter and in LoTR, so it's accurate, but he's only in LoTR for like the beginning of book 1 and the end of book 3, versus Frodo as one of the main characters.... so it's going to bug people if you call it at Bilbo.

Picture's fine.

Yup, contributing. :).

**Comment by sarahholden** [comment]
Hahaha amazing! Fixed (see above commit).

Still needs to be fixed: The fact that I don't know anything about LoTR or the Hobbit. ;)
