### ISSUE TITLE
Ch9_Functions American Football?

### ISSUE THREAD

**Issue by ZebGirouard** [sarahholden/fundamentals#126]
The second video in the Functions intro leans heavily on an American Football analogy.

Not sure if this is the best place to flag this issue, but are we pushing this curriculum outside the U.S.?  Basketball comes to mind as a more universal, and almost identical analogy.

**Comment by sarahholden** [comment]
@ZebGirouard Great point! I think this one would be more of a fix for when there's a refresh of JS Circuits. For now we're a little locked-in with those videos. @amyealmeida Thoughts?

**Comment by amyealmeida** [comment]
@ZebGirouard -- thanks for calling this out-- we definitely want to use examples that will be useful in all our various markets.  Unfortunately, videos are tough to edit in the short-term, so I will make sure this is noted in our feedback for the Javascript Circuit, and hopefully we can edit this in the near future.

**Comment by ZebGirouard** [comment]
Yeah, I get it.
