### ISSUE TITLE
Ch9_Scope_Exercise JSBin Order Is Off

### ISSUE THREAD

**Issue by ZebGirouard** [sarahholden/fundamentals#133]
@sarahholden , can you take a look at this?  The "points" exercise is well-written, but seems like the JSBin should be below the description rather than above it.  I do not understand the "Hello " + name exercise, and it seems to reference a non-existent JSBin.  Then there is the JSBin with contacts which seems orphaned.  Slack me if this description doesn't make sense, but I think if you check it out in the GitBook, you'll see what I mean.

**Comment by sarahholden** [comment]
Thanks @ZebGirouard! Those bins were initially correct, I'm not sure what happened, looks like they got updated somewhere along the way. Can you review these changes and let me know if things look good? Thanks!

**Comment by ZebGirouard** [comment]
@sarahholden , looks better, but now the numbering restarts at 1 for the second exercise.  Can you fix that?

**Comment by sarahholden** [comment]
Updated!

![screen shot 2017-02-11 at 4 36 52 pm](https://cloud.githubusercontent.com/assets/3768318/22858655/53485586-f078-11e6-824c-069257dc5477.png)

**Comment by ZebGirouard** [comment]
Beautiful, thanks @sarahholden !
