### ISSUE TITLE
Unit 2 - Assignment

### ISSUE THREAD

**Issue by sarahholden** [sarahholden/fundamentals#147]
@amyealmeida @microsarah Creating an issue for the Unit 2 Assignment since we chatted about updating the activity since we want students to create the Memory Game from scratch.

**Comment by microsarah** [comment]
Accidentally named my commit message wrong so it's now showing up here– oops! My most recent push should resolves this issues @amyealmeida @sarahholden

**Comment by sarahholden** [comment]
@microsarah Looks great! The only update I would suggest is updating that image so that it shows a blank repository, or cropping it, so students won't think that they should see a starter-code folder in their repository when they create a new one.

**Comment by amyealmeida** [comment]
@microsarah once you update the image, can you go ahead and close this issue?
