### ISSUE TITLE
Units 7+: could the 'solutions' link to the specific one and not the solutions ToC?

### ISSUE THREAD

**Issue by susiremondi** [sarahholden/fundamentals#150]
In all the exercises - examples, 7.1.1 and 7.2.1 - there's an italicized link at the bottom: _"Stuck? Check out the solutions for assistance"_

The 'solutions' link takes you to the main solutions page - the table of contents list. It'd be nice if it linked directly to the right paragraph.

It's interesting - these two, for example, are configured differently and actually seem to have different behavior.

7.1.1 links just to _/exercise-solutions.html_, so this is just to the main solutions page.

However, 7.2.2 and a few of the other have links like _/exercise-solutions.html#data-types_, which is the right id / name / anchor. It does actually look like it might jump there for about 1/100 of a second before going to the main ToC.

**Comment by sarahholden** [comment]
@susiremondi Hmm...I didn't notice the brief jump down in GitBook. 

I was adding those jump links in since they worked on GitHub, but then I realized the jumplinks don't seem to work in GitBook (or it looks like there may be a brief jump down before jumping back up). I did some research, but I couldn't find any way to link to another page then a section of that page in GitBook. If the jump down is noticeable I can remove the `#section-to-jump-to` portions from those urls.

**Comment by susiremondi** [comment]
Okay - I fixed it with caveats :).

Because it actually successfully works when you link it and just immediately jumps back up, I figured that there was something happening upon end load of the solutions page that reloads the page and puts you to the top.

So the problem is with the scripts at the bottom of the _exercise-solutions_ page. 

So I fixed it by getting rid of them, haha. Except I don't know anything about gitbook.... so I don't know what else that might have broken - I feel like taking out two entire scripts probably isn't a great idea.

I took out:

```
<script src="gitbook/app.js"></script> 
<script src="gitbook/plugins/gitbook-plugin-ga/plugin.js"></script>
```   

And it works (tested on 7.2.1, 9.2.1, and 11.2.1).

I could look at the scripts if you'd like and see if I see anything glaring; otherwise I'm just going to keep going forward reading the rest of the sections.

**Comment by sarahholden** [comment]
@susiremondi I can take a look! Did you remove them from the Gitbook files? Those recompile every time a person runs "GitBook serve" so I'm not positive that those files won't get overwritten but I think I could check out the javascript file and see if I can pinpoint the code that is making that happen.

**Comment by susiremondi** [comment]
I removed it from fundamentals/_book/exercise_solutions.html. The ones
outside the _book folder are all .md files, and I had no idea what that
was, so I figured it was automatically created and left it alone.

But aw man, you're right - if I do a ctrl-c to stop the server and then an
npm start again, the original html file is back.

Does it automatically pull the html from the md file? Which doesn't have
those two lines... so those two lines are auto-created by gitbook serve?
Bummer. I can look at the two js files too (though I'm not sure how much
help I'd be, not knowing gitbook), but I don't know which ones are
autocreated and which are actually called, so I'd need pointing in a
direction. Otherwise, good luck :).

**Comment by sarahholden** [comment]
Yeah, so GitBook grabs the content from the .md files and then compiles them into html in the _book folder, which is generated every time updates are made. I'm not sure where those JS files are coming from, but my guess is that it makes the same template for every page so I'm not sure if we could remove those scripts from one page and not the others. I'm a little unsure, too :). But there must be something in the JavaScript file that's causing that behavior. I couldn't seem to figure it out in a Google Search.

**Comment by susiremondi** [comment]
There's so much going on in this! :(. Okay, so - I looked all through both the JS files, and they're pretty terribly organised - all the variable and function names are like "a" , "b" , "c" , as opposed to like "movePage", "clickedButton", or anything at all useful. 

I looked into all the ways it's possible to reload a page with js/jquery, but neither file has a reload or refresh call, so I thought they were being reloaded with location.href=location.href (which seems to be the only remaining option and there are tons in app.js). There's also one "<a href='#'></a>". 

But it looks like when I change the app.js file to test out changing those, my changes don't carry over. Uf. ... [This save-scroll idea](http://blog.crondesign.com/2009/09/scrollfix-remember-scroll-position-when.html) also looks like it might be worth a try, but again, I can't get my app.js to save anychanges I make to it.

I think I more or less give up without further knowledge of gitbook :(.

**Comment by sarahholden** [comment]
Yeah I hate trying to pick through code that's been obfuscated. Thanks for giving it a stab! I think it should be fine for now. Hopefully on the new platform we'll have a better way of organizing solutions. But the jump link chart at the top should do for now, at least. 

Closing this one out if that's alright by you!
