### ISSUE TITLE
7.0 var vs. let and const? ECMA6?

### ISSUE THREAD

**Issue by payne-chris-r** [sarahholden/fundamentals#151]
In Boston we're using ecma6 and asking that our developers to use `let` and `const` instead of `var`. I realize this is a big change for fundamentals, but it IS the way .js is moving, and may be a good idea to start them off on this path.

**Comment by sarahholden** [comment]
Hi @payne-chris-r I think we'll leave this for now. I don't think it's harmful for students to be aware of using `var`, especially when they are Googling a JS question, as `var` will often be used in code that is found in a Google search. And then in WDI they can dig into `let` and `const`. But, maybe in the future this update would be worthwhile, or an addition to the material.
