### ISSUE TITLE
Introducing `typeof` necessary? 7.2

### ISSUE THREAD

**Issue by payne-chris-r** [sarahholden/fundamentals#152]
Knowing that `typeof` exists is nice, but I don't feel it's necessary when you're staring out.

**Comment by sarahholden** [comment]
Hi @payne-chris-r I think letting students know about `typeof` can help them "visualize" the different data types in JavaScript by seeing them in action in their console and it will be helpful for them to be aware of `typeof` before they start WDI. So keeping this in for now.
