### ISSUE TITLE
2nd `=> undefined` is confusing 7.2

### ISSUE THREAD

**Issue by payne-chris-r** [sarahholden/fundamentals#154]
```js
var name;
=> undefined
```
So lets try assigning a value to variable:
```js
var name = 'Bill';
=> undefined

name;
=> 'Bill'
```

**Comment by payne-chris-r** [comment]
if the first returns undefined (whatever is inside name), why doesn't the 2nd return 'Bill'?! (I know the answer to this, but the example may raise more questions than it answers.
Suggested edit:
```js
var name; // name is instantiated, but still undefined
```
So lets try assigning a value to a variable:
```js
var name = 'Bill'; // the variable name gets assigned the string 'Bill'

name;
=> 'Bill' // the variable `name` now is the same as writing the string 'Bill'
```

Or something like that.

**Comment by sarahholden** [comment]
@payne-chris-r Adding `=> undefined` when declaring variables was a request by another instructor since this is what students will see in their console, which makes them think they are doing something wrong. I'll work on adding a bit to the explanation here.
