### ISSUE TITLE
This isn't correct.

### ISSUE THREAD

**Issue by payne-chris-r** [sarahholden/fundamentals#160]
**IS:**
They come in two varieties, 'single-quote' (sometimes called 'string literals') and "double-quote". 
**SHOULD BE:** 
They come in two varieties, 'single-quote' and "double-quote".

**Comment by payne-chris-r** [comment]
(They are both string literals)

**Comment by amyealmeida** [comment]
@payne-chris-r can you please include the lesson number in the issue?  We don't know what this is referring to!
