### ISSUE TITLE
7.6, 8.8, 9.6 - maybe crop screenshot?

### ISSUE THREAD

**Issue by susiremondi** [sarahholden/fundamentals#163]
You have this screenshot halfway down 7.6 in the exercise for showing the console results:
![image](https://cloud.githubusercontent.com/assets/25623009/22836727/92457766-ef8b-11e6-926c-10c2002c7377.png)

You have the same screenshot in 8.8 and 9.6, right above _Pushing Code up to the Repository_.

However, console in Chrome for me by default opens in a sidebar, not in a bottom bar (I made up that term). Also, do they care about the "Concentration, also known as..." part for this exercise? So I think it'd be more universal to just show the console part. Like:

![screen shot 2017-02-10 at 12 22 02 pm](https://cloud.githubusercontent.com/assets/25623009/22836851/0f7f9f18-ef8c-11e6-82ca-59ef9b95a663.png)

and that's it.

**Comment by sarahholden** [comment]
Cropped! Thanks for the feedback, Susi.
