### ISSUE TITLE
8.5.1 - " On to the next lesson!" goes back to arrays

### ISSUE THREAD

**Issue by susiremondi** [sarahholden/fundamentals#166]
At the bottom of the page, the standard, _Feeling confident? On to the next lesson!_ should take you to 8.6, the quiz, but instead it takes you to 8.4, intro to arrays.

**Comment by sarahholden** [comment]
@susiremondi I think I might have already fixed this one (or Zeb did), would you take a look again from the latest version of Master?

**Comment by susiremondi** [comment]
Ah, I searched to see if the issue already existed, but I guess I suck at searching. Yeah, it's fixed.
