### ISSUE TITLE
9 - suggested semicolon

### ISSUE THREAD

**Issue by susiremondi** [sarahholden/fundamentals#169]
To keep javascript looking like javascript, maybe add a semicolon to the format example?

Above the bold DRY header, you have:

> Now each time an order is completed, we simply have to write:
> `orderComplete("productTitleHere", orderAmountHere)`
> and all lines of code in the orderComplete function will run.

maybe make that

> `orderComplete("productTitleHere", orderAmountHere);`

**Comment by sarahholden** [comment]
Added! Thanks Susi!
