### ISSUE TITLE
Unit 1 - Think Like a Developer

### ISSUE THREAD

**Issue by microsarah** [sarahholden/fundamentals#17]
Ready for review
https://github.com/sarahholden/fundamentals/blob/master/01_unit/think-like-a-developer.md

**Comment by amyealmeida** [comment]
@microsarah this also has some overlapping content with Unit 7 (mostly the part about Googling), but I think it is better to cover it here since that will be helpful for students to have in mind from the very beginning.

Let's talk through all this tomorrow!

**Comment by microsarah** [comment]
I agree– did we end up discussing this? Let me know if it needs any changes.

**Comment by amyealmeida** [comment]
We did discuss it but no action items for you! @sarahholden is removed the googling section from Unit 7.
