### ISSUE TITLE
9.5 - cheatsheet - suggested wording change

### ISSUE THREAD

**Issue by susiremondi** [sarahholden/fundamentals#170]
You have in the cheatsheet:

> Functions must be defined before they can be used.

However, this by your own definition is very fuzzily written. Are you just talking about function declarations or function expressions? Because this wording to me implies that no function can be called until later in the code after it's defined - which is true for what you guys are generally using (function expressions) but not true for function declarations.

Or do you mean that there must be a definition -somewhere- in the code or else it's useless?

I think maybe in your cheatsheet you can/should essentially re-paste from 9.1 (especially since it might be helpful to reiterate both kinds, since your summary only shows function expressions):

> there are two ways to define functions. Function declarations are always moved, or "hoisted," to the top of their scope by the interpreter. (Remember, the interpreter is the console in JS — the software that runs the code).
```
sayHello();

function sayHello () {
console.log('hey!');
}
```

> On the other hand, function expressions must be defined before they are called.
```
var sayHello = function () {
console.log('hey!');
};

sayHello();
```
> As a reminder, in Fundamentals, we will only be using function expressions. This is what you're more likely to use in a real world scenario.

Just a thought. On a side note, that last sentence I would doublecheck with someone that works in the real world, because that might have changed since the last time I programmed for a living.

**Comment by sarahholden** [comment]
Updated! I left out that last part since I believe function declarations are used almost as much, if not more. We just wanted to be consistent in Fundamentals and also encourage better organization of scripts.
