### ISSUE TITLE
Ch10_Assignment Phone? Odd properties in table

### ISSUE THREAD

**Issue by ZebGirouard** [sarahholden/fundamentals#173]
There are three properties for our card object: `card` (should that be `rank` to prevent ambiguity?), `suit`, and `phone`.  I'm pretty sure whoever wrote `phone` meant `cardImage`.  Also there are missing quotation marks in the image paths

**Comment by sarahholden** [comment]
@ZebGirouard I've updated things! If you do get a moment, can you review these updates? Thanks!

**Comment by ZebGirouard** [comment]
@sarahholden , looks good to me!
