### ISSUE TITLE
Ch10_Assignment Why the blockquotes?

### ISSUE THREAD

**Issue by ZebGirouard** [sarahholden/fundamentals#174]
Step 2 and 3 in the assignment have all of their sub-bullets and sub-blockquotes displayed as blockquotes.  Like, I can actually see the `-` and `>` in a blockquote instead of bullets and blockquote formatting, respectively.  I tried to fix, but my markdown skills are not good enough to solve this.

**Comment by sarahholden** [comment]
Fixed! Still not ideal, but the best I could do with that darn markdown formatting!!!

![screen shot 2017-02-11 at 4 53 11 pm](https://cloud.githubusercontent.com/assets/3768318/22858732/b06ab52c-f07a-11e6-828e-8d62e3980383.png)
