### ISSUE TITLE
Assignment Solution Link in TypeForm

### ISSUE THREAD

**Issue by sarahholden** [sarahholden/fundamentals#177]
Already done: removed assignment solutions link from sidebar.

1. Amy: Research a good place to keep the repository
2. Amy: Add link for this repository to the Typeform questionnaire 
2. Sarah: Add solution to repository

**Comment by amyealmeida** [comment]
@sarahholden @microsarah Matt B suggested putting a zip file of the solution in a Google Drive folder rather than on Github-- how do you think that would work?

**Comment by microsarah** [comment]
@amyealmeida @sarahholden I don't think this would solve the issue of the student needing to visit a different 'place' to access the solution. I also know from Circuits that some people don't use gmail (I know, gasp!) which could cause additional issues. Thoughts?

**Comment by sarahholden** [comment]
I do like the idea of Google Drive although I agree with Sarah that not everyone has access (here's looking at some of my current students haha).

Let's chat in our meeting!

**Comment by amyealmeida** [comment]
link has been added in final Typeform!
