### ISSUE TITLE
Ch11_DOM_Intro misuse of the word "literally"

### ISSUE THREAD

**Issue by ZebGirouard** [sarahholden/fundamentals#179]
I don't think this is an issue that can be fixed (just ask any teenager), but I do like the idea of something on a  webpage "literally jumping out to the user".  Fans of Poltergeist, The Ring, and Ghostbusters may enjoy this, but most users would not like this feature.

**Comment by sarahholden** [comment]
@ZebGirouard This is in the video, correct? We can log it for the future :)

**Comment by ZebGirouard** [comment]
@sarahholden , yup

**Comment by sarahholden** [comment]
Adding it to our list!
