### ISSUE TITLE
Units 7 - 11: Updating short answer questions -> multiple choice

### ISSUE THREAD

**Issue by sarahholden** [sarahholden/fundamentals#183]

**Comment by sarahholden** [comment]
@amyealmeida Theses should be ready to go! If you take a look at this pull request, you can see any updates I made in green if that's helpful: https://github.com/sarahholden/fundamentals/pull/184/files

Thank you!

**Comment by amyealmeida** [comment]
thanks so much for doing this-- all quizzes have been updated!
