### ISSUE TITLE
11.1 - mention of sibling with no explanation (wording suggestion)

### ISSUE THREAD

**Issue by susiremondi** [sarahholden/fundamentals#185]
At the bottom of 11.1, there's

![image](https://cloud.githubusercontent.com/assets/25623009/22844794/d2f5660a-efad-11e6-8844-297dd223d114.png)

You've explained child, but you haven't explained 'sibling.' It's inferrable for sure, but maybe add an example to clarify. For example (and I swapped previous and next to make the example clearer)

> nextSibling — Will find the next sibling of a selected element.
- > Note: A sibling is an element with the same parent. For example, calling 'nextSibling' on the first li in the picture above will return the second li.
> previousSibling — Will find the previous sibling of a selected element.
- > Note: For example, calling 'previousSibling' on the second li in the picture above will return the first li.

**Comment by sarahholden** [comment]
Added!
