### ISSUE TITLE
Ch11_Quiz Bunch of questions show up after 7 finished

### ISSUE THREAD

**Issue by ZebGirouard** [sarahholden/fundamentals#188]
At first, only 7 questions show up.  After answering question 7, I see 10 questions.

**Comment by ZebGirouard** [comment]
Once I answer question 10, I see 12 questions.

**Comment by ZebGirouard** [comment]
Then it says I answered 10/10 correctly.  Which I guess is right, since questions 1 and 2 were my email and my city.

**Comment by amyealmeida** [comment]
this should be fixed!
