### ISSUE TITLE
Unit 3 Quiz - Typeform issue

### ISSUE THREAD

**Issue by sarahholden** [sarahholden/fundamentals#189]
@amyealmeida I'm not sure how to fix this one in Typeform. The incorrect answers for the last to options in the very last question in the Unit 3 quiz just jump me to the bottom, without showing the response text.  

These ones:

![screen shot 2017-02-10 at 2 36 37 pm](https://cloud.githubusercontent.com/assets/3768318/22846847/8dbb2c6e-ef9e-11e6-99f4-9441ea9c3d02.png)

Thanks!

**Comment by amyealmeida** [comment]
@sarahholden just confirming this is still an issue.  In your Unit 3 Review issue, you said you made updates to the Unit 3 Quiz in Typeform. Was this resolved or do I still need to take a look?

**Comment by sarahholden** [comment]
@amyealmeida Still an issue! I updated some text in the quiz and responses, but I was careful not to make any updates that effected any logic for the quiz. Not sure why this is happening? Thanks!

**Comment by amyealmeida** [comment]
@microsarah do you mind taking a look at this? It is so weird-- no options appear when I go to add logic jumps.  I even recreated the question...

**Comment by microsarah** [comment]
@amyealmeida Fixed! Sorry I missed the correct logic on this one.
