### ISSUE TITLE
Where do we get these `images` from?

### ISSUE THREAD

**Issue by ZebGirouard** [sarahholden/fundamentals#193]
In the Unit 10 and Unit 11 assignment, we make references to `.png` files in an `images` folder.  But I don't think we ever told students how to get these images, or that they even exist.

This seems like a big problem.  Probably the biggest I have found during my QA.

**Comment by sarahholden** [comment]
Note: need to chat in our meeting Monday about where to host these images.

**Comment by sarahholden** [comment]
Updated instructions in Unit 4 assignment. Link just needs to be added here: 

![screen shot 2017-02-15 at 1 34 51 pm](https://cloud.githubusercontent.com/assets/3768318/22996419/8fcc5198-f383-11e6-8c07-d91d635970dc.png)

**Comment by sarahholden** [comment]
![screen shot 2017-02-15 at 1 40 14 pm](https://cloud.githubusercontent.com/assets/3768318/22996635/4efdef86-f384-11e6-87ea-c02324727c4c.png)
