### ISSUE TITLE
Unit 4 - Quiz - Configuration for correct # of answers on result screen

### ISSUE THREAD

**Issue by sarahholden** [sarahholden/fundamentals#197]
Hi Amy,

For some reason, when I answer all **11 questions** correctly I get this on the result screen:

![screen shot 2017-02-11 at 2 49 26 pm](https://cloud.githubusercontent.com/assets/3768318/22858132/650ee532-f069-11e6-888b-fff95eef60cd.png)

https://admin.typeform.com/form/2905679/fields/#/

**Comment by amyealmeida** [comment]
this should be fixed!
