### ISSUE TITLE
Chapter 7 - Expressions and Evaluations

### ISSUE THREAD

**Issue by sarahholden** [sarahholden/fundamentals#2]
https://github.com/sarahholden/fundamentals/blob/master/07_chapter/expressions-evals.md

@amyealmeida This lesson is ready for review! The JS Bin widgets don't show on Github in the readme, but DO show in the compiled GitBook.

Thanks!

**Comment by amyealmeida** [comment]
Thanks @sarahholden !  I embedded the videos and corrected any minor typos. Looks really nice.
