### ISSUE TITLE
ew 7.6 Create a new folder called js.

### ISSUE THREAD

**Issue by payne-chris-r** [sarahholden/fundamentals#203]
I really don't like `js` as a folder name. I think it's somewhat ok because we're just starting out, but it's the kind of thing we don't want them to get in the habit of. If it's possible to change, I'd recommend it, not a huge deal--just a bad habit.

**Comment by sarahholden** [comment]
I think this is okay starting out - short and descriptive. And probably not worth the time to update everywhere.
