### ISSUE TITLE
7.6 NO -- Bad Habit. git add -A

### ISSUE THREAD

**Issue by payne-chris-r** [sarahholden/fundamentals#205]
This is another thing that they learn in fundamentals that I think is a bad habit. When you're adding things to staging in git, you should be adding your files one at a time so you are methodical and understanding everything that's being added to your repo. Using git add -A eliminates that methodicalness and can cause issues.
This is kind of similar to #203 in that it's just a bad habit to start off with, but not a deal breaker for beginners.

**Comment by sarahholden** [comment]
Totally agree that this can be a bad habit without fully understanding what's happening. We go over this in an earlier unit and for now I think I'll keep git add -A - it would be pretty hard to maintain things if we listed out all the files they should stage each time, or it would be likely that students could miss some. Just want to make things as easy as possible for students who might have trouble with these steps.
