### ISSUE TITLE
7.6 git commit -m 'created game logic'

### ISSUE THREAD

**Issue by payne-chris-r** [sarahholden/fundamentals#206]
Same vein as #205. It's a bad habit. You can't write a thoughtful commit message using `-m`. This is something we teach once they get to WDI, and again not a deal breaker, but it's still a bad habit.

**Comment by sarahholden** [comment]
Another one I'll label as "wontfix" for now, with the possibility of eventually looping back. It's an easy way for beginners to add messages all in one line to get the workflow down and the amount of time updating and adding additional instructions would most likely outweigh the benefits. But great that they will get into more detail in WDI.
