### ISSUE TITLE
Unit 8 - Switch and Ternary Operators Exercise

### ISSUE THREAD

**Issue by sarahholden** [sarahholden/fundamentals#21]
https://github.com/sarahholden/fundamentals/blob/master/08_unit/switch-ternary-exercise.md

@amyealmeida Ready for review!

This is a new exercise with some content borrowed and updated from Circuits, and some brand new.

1 known issue:
- Need to fix JS Bin starter code. Still can't embed JS Bin without a pro account (Leaving myself assigned as well until this is resolved).

**Comment by amyealmeida** [comment]
I made a small edit, but other than that looks really good!  I will leave this open until the jsbin problem is resolved.

**Comment by sarahholden** [comment]
@amyealmeida Fixed all JS Bin issues. Also updated the intro for all exercises to make sure students don't get tripped up with the different panels in JS Bin. Take a look and let me know if those intros look alright!
