### ISSUE TITLE
8.1 && and || return values

### ISSUE THREAD

**Issue by payne-chris-r** [sarahholden/fundamentals#210]
This is not a dealbreaker. But to me, learning what these operators return isn't what's important, it's understanding how they work. && is equating whether both things are true, || is equating whether one of the things are true, etc. 
I guess I just feel like the returning of values is not as important as understanding what they do for && and || until later on. Yes, there are quirks, but they aren't as important for beginners?

**Comment by jrhorn424** [comment]
> But to me, learning what these operators return isn't what's important, it's understanding how they work.

Is this semantics? If so, what is correct? Expressions don't have `return`, only functions. Expressions do, however, "evaluate" to a single a value, which is the point of learning how to read expressions.

Given the word "evaluate", I don't see how the following is wrong, or how it conflicts with what is mentioned in fundamentals.

> && is equating whether both things are true, || is equating whether one of the things are true, etc.

I'm not sure learning to read expressions is in scope for fundamentals, but being exposed to the concepts are certainly in scope.

@payne-chris-r You used the word "understand" twice. You know better. ;)
