### ISSUE TITLE
Unit 1 - Intro

### ISSUE THREAD

**Issue by microsarah** [sarahholden/fundamentals#23]
Ready for review
https://github.com/sarahholden/fundamentals/blob/master/01_unit/developer-foundations-intro.md

**Comment by amyealmeida** [comment]
@microsarah The video used here is the same video Sarah Holden uses in the Unit 7 intro.  I think it actually fits a little more logically with the Unit 7 content.  

I am adding this to our notes to discuss tomorrow!

**Comment by microsarah** [comment]
@amyealmeida let me know what you think of this intro!

**Comment by amyealmeida** [comment]
This looks good but I'd love to dig a little deeper into _why_ students need to know about this stuff.  For example, is knowing about ISP addresses and servers going to help them later make decisions that will make their website faster? or more secure?  Is it going to help them in their career to be able to carry on knowledgeable conversations about the backbone of web applications?  

Maybe none of the above is true, but something along those lines!

**Comment by amyealmeida** [comment]
@microsarah just realized I didn't tag you in this so not sure if you saw it!

**Comment by microsarah** [comment]
Np @amyealmeida let me know how this edit sounds!

**Comment by amyealmeida** [comment]
love it!
