### ISSUE TITLE
9.2 Refactor?

### ISSUE THREAD

**Issue by payne-chris-r** [sarahholden/fundamentals#232]
```diff
var sum = function (x, y) {
-  return x + y;
+  var result = x + y;
+  return result;
- }
+ };
```

**Comment by payne-chris-r** [comment]
I'm not sure which is more confusing to beginners-- a `return` returning the sum of something, or declaring a new variable in a function. I think the above example is slightly better, but I don't have a very strong opinion about it.

Either way the `;` should be added though!

**Comment by sarahholden** [comment]
Previously updated on master. Thanks!
