### ISSUE TITLE
Unit 7 - Intro

### ISSUE THREAD

**Issue by sarahholden** [sarahholden/fundamentals#24]
https://github.com/sarahholden/fundamentals/blob/master/07_unit/js-intro.md

@amyealmeida Ready for review!

**Comment by amyealmeida** [comment]
Great-- the only thing here is that there is some repetition between some of the content, and content that appears in Chapters 1 and 2.  I am adding this to the list of things to discuss during tomorrow check-in.

**Comment by sarahholden** [comment]
@amyealmeida Hey Amy! I've removed the tools/resources section for the intro here. Let me know how this looks and if I've removed anything that is repetitive :)
