### ISSUE TITLE
10.2 Add bullet

### ISSUE THREAD

**Issue by payne-chris-r** [sarahholden/fundamentals#250]
## Accessing Methods
Next, ....

If we...

```js

var myBicycle = {
...
// Here we are "calling" the accelerate method.
myBicycle.accelerate(); 
// => "Zoom zoom!"
```

* Here, we use the object name `myBicycle`, followed by a period, followed by the method name, followed by parenthesis.
* Think about it his way, what is `myBicycle`? An object! What is `myBicycle.accelerate`? A function! How do you _invoke_ a function?  You add `()`s to the end of the function name! So in order to invoke a method, you write `myBicycle.accelerate();`

^^^ ADD THIS BULLET

**Comment by sarahholden** [comment]
Great addition. Thanks Chris!
