### ISSUE TITLE
Unit 1.2 Intro to Programming Languages - Lyft doesn't look like that anymore

### ISSUE THREAD

**Issue by ZebGirouard** [sarahholden/fundamentals#255]
Lyft doesn't look like that anymore.  I will update with a more recent version, cross-checking with a couple other PCs to make sure it's not an A-B redirected site, or at least has some consistent things.

**Comment by sarahholden** [comment]
Perfect, thank you! Here's what it looks like for me if that helps with the A-B determination: 

![screen shot 2017-02-15 at 11 15 39 am](https://cloud.githubusercontent.com/assets/3768318/22991125/2870af5c-f370-11e6-9dd1-90e2125735b9.png)

**Comment by ZebGirouard** [comment]
Thanks @sarahholden , that's what we see here.
