### ISSUE TITLE
Unit 7 - Pseudocode Lesson

### ISSUE THREAD

**Issue by sarahholden** [sarahholden/fundamentals#27]
https://github.com/sarahholden/fundamentals/blob/master/07_unit/pseudocode.md

@amyealmeida Ready for review!

Pulled content from JSC, kept some of the content from the previous version of Fundamentals.

This lesson follows after the JS Intro lesson, where a few of the terms used are introduced.

**Comment by amyealmeida** [comment]
Good stuff!
