### ISSUE TITLE
Unit 9 - Scope

### ISSUE THREAD

**Issue by sarahholden** [sarahholden/fundamentals#34]
https://github.com/sarahholden/fundamentals/blob/master/09_unit/scope.md

@amyealmeida Ready for review!

**Comment by amyealmeida** [comment]
@sarahholden the lesson looks good, but for the scope exercise, I don't actually see any directions for the students to follow.  Were they supposed to be within the JSBin, or listed out below?

**Comment by sarahholden** [comment]
Hey @amyealmeida sorry for the confusion! This was for the lesson only and will create a separate issue for the exercise. I can lump those together going forward if it's easier!

Thanks!
