### ISSUE TITLE
Unit 11 - Manipulating the DOM

### ISSUE THREAD

**Issue by sarahholden** [sarahholden/fundamentals#46]
https://github.com/sarahholden/fundamentals/blob/master/11_unit/manipulating-the-dom.md

@amyealmeida Ready for review!

When I was putting this lesson together it was getting pretty long with DOM manipulation and events all in one lesson. I think it might make sense to split events into a separate lesson so I've created another file for events. We can chat about this next week!

**Comment by amyealmeida** [comment]
I agree-- that makes sense.
