### ISSUE TITLE
Assignments for Units 7 - 11

### ISSUE THREAD

**Issue by sarahholden** [sarahholden/fundamentals#66]
@amyealmeida Ready for review!

I think it makes sense to have solution code accessible for each assignment since the assignments build on each other and I don't want students to get stuck. See the section I've added to the bottom of each assignment file. I also think there's some learning potential in comparing one's code agains the solution. Let me know what you think!

Also, feel free to create a separate issue for any issues related to a particular assignment if it's easier!

**Comment by amyealmeida** [comment]
@sarahholden is the screenshot for the deliverable in Assignment 8 and Assignment 9 supposed to be the exact same?

**Comment by sarahholden** [comment]
@amyealmeida That's correct! The deliverable will be the same, but they are adding in functions for assignment 9 to make the project more scalable so the JavaScript for those will be different.
