### ISSUE TITLE
Ch7_Expressions_and_Evaluations why console.log mentioned?

### ISSUE THREAD

**Issue by ZebGirouard** [sarahholden/fundamentals#76]
I am not sure why we need the stuff in parentheses below.  We didn't say anything about `console.log()` before...

`As you can see, putting single or double quotation marks around a value turns it into a string. (Again, don't worry about the console.log() command for now).`

Not sure how to resolve.

**Comment by sarahholden** [comment]
Thanks for catching that @ZebGirouard! I will work on adding in a section on console.log in the beginning of Unit 7 and then removing this comment in parenthesis.
