### ISSUE TITLE
Ch7_Quiz What's up with the asterisks?

### ISSUE THREAD

**Issue by ZebGirouard** [sarahholden/fundamentals#78]
There are asterisks on all the questions, because, I guess, they are required questions.  But this is really confusing when they fall in code blocks like:

`9 % 3*`

Not sure how to fix this, but it'll definitely confuse students.

**Comment by sarahholden** [comment]
@amyealmeida Thoughts?

**Comment by amyealmeida** [comment]
the asterisks denote a required question.  They should all be required. Fixing this now on all quizzes.
