### ISSUE TITLE
Ch7_Quiz "Not Quite" before I even get there

### ISSUE THREAD

**Issue by ZebGirouard** [sarahholden/fundamentals#79]
As I go through the quiz, I notice it's already yelling at me for short-answer questions that are left blank.  Since all questions I haven't gotten to yet are blank, it's saying I have a wrong answer before I've even tried.

Not sure how to fix this, but it will definitely frustrate students.

**Comment by ZebGirouard** [comment]
Also, this carries through to my final grade.  There were two short-answer questions, so my maximum possible score is 8/10.  This will make students want to kill someone.

**Comment by sarahholden** [comment]
Assigning to myself for now. We've chatted and the decision is to make all quiz questions multiple-choice. Noting here for the record.

**Comment by sarahholden** [comment]
Reassigning to Amy to fix the logic now that all quiz questions are updated to multiple choice.

**Comment by amyealmeida** [comment]
fixed!
