### ISSUE TITLE
Lesson 7 - Data Types Exercise

### ISSUE THREAD

**Issue by sarahholden** [sarahholden/fundamentals#8]
@amyealmeida Ready for review!

Exercise: https://github.com/sarahholden/fundamentals/blob/master/07_unit/data-types-exercise.md
Solutions sheet: https://github.com/sarahholden/fundamentals/blob/master/exercise-solutions.md

Old exercise was confusing so replaced with a new exercise (going to note which exercises I've replaced so we can keep track).

Known issues:

- JS Bin doesn't auto-run the code for me. Not even on the live Fundamentals. Not sure what the solution would be, aside from just having students run their code in the console.
- I formatted the solution for this one a bit differently, putting the question alongside the answer in the solutions sheet. Does this make sense? I figure it's easier to read them side-by-side. Also, I haven't updated the number, but it might make more sense to add a lesson name instead of number? Honestly, the whole sheet is weird and this might be an area where it would be useful to have your help reformatting or thinking of a better solution. Having the numbers here is just another place we'll have to update if those change in the future.

Thanks!

**Comment by amyealmeida** [comment]
@sarahholden Yes, having the question next to the answer on the solutions sheet makes a lot of sense! Much better experience for students.  I am adding the solutions sheet to a list of things to discuss this afternoon.  I am happy to reformat it once we decide on the best way.  

At the very least, there should be jump links at the top so students don't have to scroll down to find the right solution!

**Comment by sarahholden** [comment]
Perfect, thanks @amyealmeida!

And I think I figured out the JS Bin thing - but the instructions were super confusing!! I'll update the JS Bin instructions in the intro to hopefully avoid some confusion. Maybe add a gif in there or something to show students what to do.
