### ISSUE TITLE
Ch7_Assignment i.e. not same as e.g.

### ISSUE THREAD

**Issue by ZebGirouard** [sarahholden/fundamentals#81]
Personal pet peeve of mine.  I don't know how this started, but it's all over the place.

I.e. = id est = "that is"

e.g. = exempli gratia = "examples given"

This is literally and definately my biggest grammar beef with our curriculum.  Their, I said it.

**Comment by sarahholden** [comment]
Haha. But really, thanks for the feedback. Is this the only place you've noticed this in Fundamentals, or are there other places? I can do a sweep if needed.

**Comment by ZebGirouard** [comment]
@sarahholden , this time through, this is the only place, but there were maybe 7 of them the last time I looked through Fundamentals and over twice that when I went through the instructor training circuit back in early June.

**Comment by sarahholden** [comment]
Fixed here. Thanks so much!
